# Generated by Django 5.1.2 on 2024-10-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0002_petowners_address_alter_petowners_create_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petowners',
            old_name='name',
            new_name='nome',
        ),
    ]
