# Generated by Django 5.1.2 on 2024-10-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0003_rename_name_petowners_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petowners',
            old_name='id_pet_owners',
            new_name='id_pet_owner',
        ),
    ]
