# Generated by Django 5.1.1 on 2024-10-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_appaccount_is_staff_alter_appaccount_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appaccount',
            old_name='user_id',
            new_name='id',
        ),
    ]
