# Generated by Django 5.1.1 on 2024-10-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_user_id_appaccount_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appaccount',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
