# Generated by Django 5.1.1 on 2024-10-03 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_appaccount_is_active_alter_appaccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appaccount',
            name='id',
            field=models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
