# Generated by Django 5.1.1 on 2024-10-09 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_appaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appaccount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
