# Generated by Django 5.1.2 on 2024-10-28 03:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet_owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(null=True)),
                ('sintomas', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoMedico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observacoes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vermifugo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoencaDocumentada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observacao', models.TextField(null=True)),
                ('data_diagnostico', models.DateTimeField()),
                ('status', models.CharField(choices=[('em_tratamento', 'Em tratamento'), ('curado', 'Curado'), ('em_monitoramento', 'Em monitoramento'), ('sem_diagnostico', 'Sem diagnóstico')], max_length=50)),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.doenca')),
                ('historico_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doencas_administradas', to='pet.historicomedico')),
            ],
        ),
        migrations.CreateModel(
            name='Cirurgia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('resultado', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha'), ('em_recuperacao', 'Em recuperação'), ('sem_informacao', 'Sem informação')], max_length=100)),
                ('historico_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirurgias_administradas', to='pet.historicomedico')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('especie', models.CharField(max_length=255)),
                ('raca', models.CharField(max_length=255)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Femea')], max_length=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_owners.petowner')),
            ],
        ),
        migrations.AddField(
            model_name='historicomedico',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
        ),
        migrations.CreateModel(
            name='MedicamentoAdministrado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observacao', models.TextField(null=True)),
                ('data_aplicacao', models.DateTimeField()),
                ('data_reforco', models.DateTimeField(blank=True, null=True)),
                ('historico_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.historicomedico')),
                ('vacina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.vacina')),
                ('vermifugo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.vermifugo')),
            ],
        ),
    ]
