# Generated by Django 5.1.2 on 2024-10-20 05:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet_owners', '0002_petowners_address_alter_petowners_create_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doecas',
            fields=[
                ('doencas_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('sintomas', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoMedico',
            fields=[
                ('historico_medico_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observacoes', models.TextField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacinas',
            fields=[
                ('vacina_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vermifugos',
            fields=[
                ('vermifugos_id', models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoencasDocumentadas',
            fields=[
                ('doencas_documentadas_id', models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_diagnostico', models.DateTimeField()),
                ('status', models.CharField(choices=[('em_tratamento', 'Em tratamento'), ('curado', 'Curado'), ('em_monitoramento', 'Em monitoramento'), ('sem_diagnostico', 'Sem diagnóstico')], max_length=50)),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.doecas')),
                ('historico_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.historicomedico')),
            ],
        ),
        migrations.CreateModel(
            name='Cirurgia',
            fields=[
                ('cirurgia_id', models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('resultado', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha'), ('em_recuperacao', 'Em recuperação'), ('sem_informacao', 'Sem informação')], max_length=100)),
                ('historico_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.historicomedico')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('especie', models.CharField(max_length=255)),
                ('raca', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Femea')], max_length=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('pet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_owners.petowners')),
            ],
        ),
        migrations.AddField(
            model_name='historicomedico',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
        ),
        migrations.CreateModel(
            name='VacinasAdministradas',
            fields=[
                ('vacinas_administradas_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_aplicacao', models.DateTimeField()),
                ('data_reforco', models.DateTimeField(blank=True, null=True)),
                ('historico_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.historicomedico')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.vacinas')),
            ],
        ),
        migrations.CreateModel(
            name='VermifugosAdministrados',
            fields=[
                ('vermifugos_administrados_id', models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_aplicacao', models.DateTimeField()),
                ('data_reforco', models.DateTimeField(blank=True, null=True)),
                ('historico_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.historicomedico')),
                ('vermifugo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.vermifugos')),
            ],
        ),
    ]
