# Generated by Django 5.1.2 on 2024-10-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
