# Generated by Django 5.1.2 on 2024-10-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_pet_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='doencasdocumentadas',
            name='observacao',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vacinasadministradas',
            name='observacao',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vermifugosadministrados',
            name='observacao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doecas',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
