# Generated by Django 5.1.2 on 2024-10-21 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_doencasdocumentadas_observacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doecas',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='doecas',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='vacinas',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='vacinas',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='vermifugos',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='vermifugos',
            name='update_at',
        ),
    ]
