# Generated by Django 5.1.2 on 2024-10-23 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_rename_doecas_doencas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirurgia',
            name='historico_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirurgias_administradas', to='pet.historicomedico'),
        ),
        migrations.AlterField(
            model_name='doencasdocumentadas',
            name='historico_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doencas_administradas', to='pet.historicomedico'),
        ),
        migrations.AlterField(
            model_name='vacinasadministradas',
            name='historico_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas_administradas', to='pet.historicomedico'),
        ),
        migrations.AlterField(
            model_name='vermifugosadministrados',
            name='vermifugo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vermifugos_admistrados', to='pet.vermifugos'),
        ),
    ]
