# Generated by Django 5.1.2 on 2024-10-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_rename_vermifugos_id_vermifugos_vermifugo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vermifugosadministrados',
            old_name='vermifugos_administrados_id',
            new_name='vermifugo_administrado_id',
        ),
    ]
