# Generated by Django 5.1.2 on 2024-10-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_rename_vermifugos_administrados_id_vermifugosadministrados_vermifugo_administrado_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doencas',
            old_name='doencas_id',
            new_name='doenca_id',
        ),
    ]
