# Generated by Django 5.1.2 on 2024-10-27 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_rename_doencas_id_doencas_doenca_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doencas',
            new_name='Doenca',
        ),
        migrations.RenameModel(
            old_name='DoencasDocumentadas',
            new_name='DoencaDocumentada',
        ),
        migrations.RenameModel(
            old_name='Vacinas',
            new_name='Vacina',
        ),
        migrations.RenameModel(
            old_name='VacinasAdministradas',
            new_name='VacinaAdministrada',
        ),
        migrations.RenameModel(
            old_name='Vermifugos',
            new_name='Vermifugo',
        ),
        migrations.RenameModel(
            old_name='VermifugosAdministrados',
            new_name='VermifugoAdministrado',
        ),
    ]
